# Generated by Django 2.2.5 on 2019-10-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_cord', models.IntegerField(default=0)),
                ('y_cord', models.IntegerField(default=0)),
            ],
        ),
    ]
