# Generated by Django 2.2.5 on 2019-10-09 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cords',
            name='x_cord',
        ),
        migrations.RemoveField(
            model_name='cords',
            name='y_cord',
        ),
    ]
