# Generated by Django 2.2.5 on 2019-10-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0002_auto_20191009_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='cords',
            name='latitude',
            field=models.FloatField(default=150),
        ),
        migrations.AddField(
            model_name='cords',
            name='longitude',
            field=models.FloatField(default=150),
        ),
        migrations.AddField(
            model_name='cords',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distance.Cords')),
            ],
        ),
    ]
