# Generated by Django 2.2.5 on 2019-10-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0003_auto_20191009_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cords',
            name='name',
        ),
        migrations.AddField(
            model_name='cords',
            name='dis',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cords',
            name='user_name',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Length',
        ),
    ]
