# Generated by Django 2.2.5 on 2019-10-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance', '0004_auto_20191016_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cords',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cords',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
